backend/yaga/config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :userauths
  resources :users

end

backend/yaga/app/models/userauth.rb
class Userauth
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

backend/yaga/app/controllers/userauths_controller.rb
class UserauthsController < ApplicationController
  before_action :set_userauth, only: [:show, :edit, :update, :destroy]

  # GET /userauths
  # GET /userauths.json
  def index
    @userauths = Userauth.all
  end

  # GET /userauths/1
  # GET /userauths/1.json
  def show
  end

  # GET /userauths/new
  def new
    @userauth = Userauth.new
  end

  # GET /userauths/1/edit
  def edit
  end

  # POST /userauths
  # POST /userauths.json
  def create
    @userauth = Userauth.new(userauth_params)

    respond_to do |format|
      if @userauth.save
        format.html { redirect_to @userauth, notice: 'Userauth was successfully created.' }
        format.json { render :show, status: :created, location: @userauth }
      else
        format.html { render :new }
        format.json { render json: @userauth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userauths/1
  # PATCH/PUT /userauths/1.json
  def update
    respond_to do |format|
      if @userauth.update(userauth_params)
        format.html { redirect_to @userauth, notice: 'Userauth was successfully updated.' }
        format.json { render :show, status: :ok, location: @userauth }
      else
        format.html { render :edit }
        format.json { render json: @userauth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userauths/1
  # DELETE /userauths/1.json
  def destroy
    @userauth.destroy
    respond_to do |format|
      format.html { redirect_to userauths_url, notice: 'Userauth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userauth
      @userauth = Userauth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userauth_params
      params.fetch(:userauth, {})
    end
end

backend/yaga/app/helpers/userauths_helper.rb
module UserauthsHelper
end

backend/yaga/app/views/userauths/_form.html.erb
<%= form_for(@userauth) do |f| %>
  <% if @userauth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userauth.errors.count, "error") %> prohibited this userauth from being saved:</h2>

      <ul>
      <% @userauth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/yaga/app/views/userauths/edit.html.erb
<h1>Editing Userauth</h1>

<%= render 'form' %>

<%= link_to 'Show', @userauth %> |
<%= link_to 'Back', userauths_path %>

backend/yaga/app/views/userauths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Userauths</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userauths.each do |userauth| %>
      <tr>
        <td><%= link_to 'Show', userauth %></td>
        <td><%= link_to 'Edit', edit_userauth_path(userauth) %></td>
        <td><%= link_to 'Destroy', userauth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userauth', new_userauth_path %>

backend/yaga/app/views/userauths/new.html.erb
<h1>New Userauth</h1>

<%= render 'form' %>

<%= link_to 'Back', userauths_path %>

backend/yaga/app/views/userauths/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_userauth_path(@userauth) %> |
<%= link_to 'Back', userauths_path %>